Update Visualtest - Fix #19
darsnack/SpikingNN.jl pull request #20
Opened 2020-07-29 05:24 UTC by RashikaKarki

2020-08-05 04:07 UTC, RashikaKarki commented
@darsnack I believe visual regression test can now pass. Could you give it a quick review.

2020-08-05 16:04 UTC, darsnack commented
Can you look at the `visualtest-issue-19` branch in the main repo? I added a commit to fix some dependency issues, but it seems I cannot commit directly to your branch. FYI next time you should check the box to allow commits from maintainers.

2020-08-09 17:34 UTC, darsnack commented
Bump @RashikaKarki

2020-08-09 18:00 UTC, RashikaKarki commented
@darsnack Would make sure to check the box on other PR's. Could you review the PR? I think I have added everything from the commit you were refering to.

2020-08-09 18:29 UTC, darsnack requested changes

2020-08-09 18:29 UTC, darsnack commented on Project.toml
> +Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
This should be under `[deps]` and `[extras]`.

2020-08-09 19:53 UTC, merged